liquidmetal-dev/flintlock

.codecov.yml
.github/workflows/test.yml
.gitignore
Makefile
infrastructure/containerd/image_service_test.go
infrastructure/containerd/testdata/config.toml

Track the code coverage over time. This change adds a unit-test with coverage makefile target and updates the test GHA workflow to upload the results to codecov
Fixes #80 
**Checklist**:
**Release note**:
```release-note
NONE
```

chore: added test coverage and upload codecov

---

.github/workflows/stale.yml

Added new GitHub actions workflow to mark issues and PRs as stale and to
automatically close issues.
The lables used are inline with those from the kubernetes project.
Fixes #86 
**Checklist**:
**Release note**:
```release-note
NONE
```

feat: added stale issue/pr GHA workflow

---

.github/workflows/release.yml

Changed the name of the binaries to retrieve after the build during the
release workflow as it was incorrect.
Fixes #

fix: incorrect binary name in release

---

internal/command/gw/gw.go
internal/command/root.go
internal/command/run/run.go
internal/version/version.go

The `version` subcommand without any flags prints out a general version
information, good to check what version we have.
❯ ./bin/flintlockd_amd64 version
flintlock v0.1.0-alpha.1-11-af7a1a9
The `version` subcommand with `--short` flag prints out only the
version, useful for scripting.
❯ ./bin/flintlockd_amd64 version --short
v0.1.0-alpha.1-11-af7a1a9
The `version` subcommand with `--long` flag prints out a detailed version
information, useful for bug reports.
❯ ./bin/flintlockd_amd64 version --long
flintlock
Version:    v0.1.0-alpha.1-12-gaf7a1a9
CommitHash: af7a1a9
BuildDate:  2021-11-03T11:38:43Z
== Why a subcommand and not a `-v` or `-V` flag?
Because it can be confusing. Some applications are using `-v` for
version, some are using `-V` for …

feat: add version subcommand

---

go.mod
go.sum

We are not using the mongodb driver at all, but dependabot is crying.
Checked if ginkgo has a newer version, but v1.16.5 is still the latest
version.
GHSA: https://github.com/advisories/GHSA-f6mq-5m25-4r72
CVE: https://nvd.nist.gov/vuln/detail/CVE-2021-20329
CVSS: 6.8 Moderate | CVSS:3.1/AV:N/AC:H/PR:L/UI:N/S:U/C:H/I:H/A:N
**Checklist**:

security: Update indirect dependency: mongo-driver

---

.github/workflows/pr_size.yml

This change removes the configured message when a PR is an XL size. This
is generating a lot of noise on PRs.
Fixes #

chore: remove the message on XL pr

---

.github/workflows/nightly_e2e.yml

This updates the e2e workflow to run the new tool.
Don't merge yet as I just decided I want to add a slack alert.
part of https://github.com/weaveworks/flintlock/issues/146

Update the nightly e2e workflow

---

test/tools/metal.py
test/tools/test.py

Extend the `run_ssh_command` method in the python test tool to pass in a value to allow/disallow
errors being recognised from the executed command
closes https://github.com/weaveworks/flintlock/issues/214

Ensure that test failures cause CI failure

---

.github/workflows/nightly_e2e.yml

Apparently the format is `<link|text>` not `[text](link)`.
No merge testing now

Format link in slack message correctly

---

.github/workflows/codeql-analysis.yml

Code scan is good.
Fixes #84
The skipped check:
> The very first time code scanning is run and if it is on a pull request, you will probably get a message mentioning a "missing analysis". This is expected.
> Source: https://github.com/github/codeql-action#note-on-missing-analysis-message
**Checklist**:

chore(security): Run CodeQL scan on PRs and on schedule

---

hack/scripts/payload/CreateMicroVM.json
pkg/validation/validate.go
pkg/validation/validate_test.go
test/e2e/utils/utils.go

The firecracker docs say that only you can only specify either a root
volume or an initrd. However, when we remove the root volume and only
have initrd (or vice-versa) the mvm will not start. 🤷‍♀️ 
We are not entirely sure what is happening yet, so for now we are going
to disable the validation and continue using both a root vol and
initrd. It's more of a guideline than an actual rule anyway 😉 
There is a separate ticket to track the investigation and potential fix
here: https://github.com/weaveworks/flintlock/issues/219
(Also added a missing test, the removed bit also was not covered so we
should remember to add one when/if we put it back)
Disables a volume validation check for the timebeing while we figure out the above issue. If we leave it in …

Disable root volume validation

---

core/plans/microvm_create_update.go
core/plans/microvm_delete.go
core/steps/microvm/create.go
core/steps/microvm/start.go

The plan list must be cleared from memory between runs so that the plan
completes and the state is saved. This keeps us from falling into an
infinite loop.
Done as a function to emphasise importance!
Fixes https://github.com/weaveworks/flintlock/issues/213
You are all very special
**Checklist**:

fix: ensure create plan is executed once

---

core/steps/network/interface_create.go
infrastructure/network/network_service.go

There is a problem with using an auto generated mac address with a macvtap interface. The
kernel appears to change the mac address from what it was originally
created with. The firecracker and cloud init configuration contain the original mac address.
When the guest boots and cloud-init gets to configure the network the
mac address has changed and this then causes the network configuration to fail as it can't
match on the mac address.
We need to find actual evidence of the above, but this has been a known
behaviour with other types of interface and for the those the advice is
to specify a mac address when you create the interface.
This change will use the `guest_mac` if it's specified for the mac
address on the host if the interface type is macvtap. …

fix: set mac address for macvtap if specified

---

.github/workflows/nightly_e2e.yml
CONTRIBUTING.md
test/e2e/README.md
test/e2e/e2e_test.go
test/e2e/utils/params.go
test/e2e/utils/runner.go

I have added the initial frame for custom test flags.
So far just the options to:
- Skip setting up the devmapper thinpool
- Skip deleting VMs
- Skip all teardown steps
- Set log level for containerd
- Set log level for flintlockd
Unfortunately custom test flags can only be added on `init()` which is
bleh but I don't see another nice was of doing this.
These flags can only be used while running `go test ...` directly.
This means you cannot pass in flags as part of a `make` or a
`docker run -it ...` command, but you can just call `go test etc` from inside the
container or in the metal host and configure what you like.
My next step is some more work around the python tooling so that these
(and more) options can be passed up.
part of https://github.com/weaveworks/flintlock/issues/146

chore(test): Add configurable opts to e2e tests

---

.github/workflows/deploy-docs.yaml

It's annoying, every time I update my fork, I get a notification about the failed GitHub Action. It tries to use a secret with SSH key, but I don't have one on my fork.
Fixes  #250
**Checklist**:

Disable Documentation site publish if it's a forked repo

---

docs/adr/0234-update-api.md

Add ADR detailing the decision to not provide support for **any** in-place updates to running MicroVMs. See #234 for discussion related to this ADR.
Fixes #193

docs: add adr to provide no support for in-place microvm updates

---

.github/workflows/release.yml
docs/releasing.md

We should not release anything unless we know it is at least not
catastrophically broken.
Fixes #
**Checklist**:

Run the e2es as part of the release process

---

Makefile
test/e2e/README.md
test/e2e/test.sh
test/tools/README.md
test/tools/config.py
test/tools/example-config.yaml
test/tools/metal.py
test/tools/requirements.txt
test/tools/run.py
test/tools/schema.yaml
test/tools/test.py

**Note: the last 2 commits are file formatting only and disguise other things which have happened**
This PR adds a bit of nice UX to the e2e python tool.
Users can now pass a config file:
```
./test/tools/run.py -c <path to file>
```
Which looks like this:
```yaml
---
org_id: "test-org" # required
project: "test-project" # or project ID
test:
skip_delete: false # skip the test cleanup and process teardown steps
skip_teardown: false # skip tearing down the equinix infra
skip_dmsetup: true # skip the thinpool setup, this should always be true for equinix
containerd_log_level: "debug"
flintlock_log_level: "2"
device:
name: "test-device" # omit if device.id set
id: "abcdef123456" # set if using existing device
ssh_key_name: "test-key"
userdata: "echo …
```

chore(test): Add config file option to e2e metal tooling

---

docs/adr/0241-opinionated-api-changes.md

This PR adds the accepted ADR for Opinionated API Changes and Rational Defaults as per discussions #241.

docs: add ADR for opinionated API changes

---

docs/quick-start.md
hack/scripts/devpool.sh
hack/scripts/direct_lvm.sh
test/tools/config/config.py

Using loop devices for devmapper's thinpool is not recommended for
production.
Real block devices are required to back thinpools in production.
This PR:
- adds an alternative script which users can run if they want a
production-ready setup. The script will take a given free device and
create the required physical and logical volumes, formatting them into
thinpool storage.
- this device can also be provided via an environment variable, which
makes it easier to use the script in the tooling userdata
- updates the quickstart docs to include the option.
- adds the script to the equinix tooling userdata so that equinix vms
are bootstrapped with direct-lvm by default.
- changes the default machine created by the tooling so that a type
with a spare disk …

feat: Add script to setup direct-lvm mode for containerd

---

test/e2e/README.md
test/e2e/utils/params.go
test/e2e/utils/runner.go
test/tools/config/config.py
test/tools/config/schema.yaml
test/tools/example-config.yaml
test/tools/test/runner.py

In the test code:
- Adds a new `-thinpool` custom flag to the e2e tests. This
lets users set a thinpool name, useful for if they want to use
one they made earlier or don't want to conflict with an
existing one.
- If using with an existing one, users should set the
`-skip.setup.thinpool` flag so they don't have some random
pool made
In the python tool:
- Previously `skip_dmsetup` was under `test` in the tool config file. This
was to disable the loopdevice thinpool setup done by the e2e test suite.
Disabling the test level dmsetup should always be True when running in
Equinix, so I have hardcoded it.
- There may be a case in which the runner wants to disable the direct_lvm
thinpool setup, so that option is now available and grouped under
`device` in …

feat(test): Wire e2e tests to use direct lvm thinpool for containerd

---

test/tools/config/config.py
test/tools/config/schema.yaml
test/tools/example-config.yaml
test/tools/metal/error.py
test/tools/metal/welder.py
test/tools/run.py

This changes the config so that a list of facilities will be tested to
ensure that there is capacity for device creation.
This gives us some resilience in the nightly e2e tests, although if
there is no capacity anywhere then they will still fail.
I had wanted to use a list of metros instead, which would have left
Equinix to find an appropriate facility, but the package I am using to
hit the Equinix API has a bug in that method (I've put in a PR). I have removed setting the
metro as an option as I did not feel like dealing with that logic right
now. Also I am not really sure which takes precedence if you set both on
the request. Metro I think?
**Which issue(s) this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close the issue(s) when PR gets …

feat(test): Check capacity of facility before creating device

---

.github/workflows/nightly_e2e.yml
test/tools/config/config.py
test/tools/config/schema.yaml
test/tools/config/userdata.sh
test/tools/example-config.yaml

Config:
```yaml
repo:
username: callisto13
branch: my-test-branch
```
will clone my fork of flintlock at that branch onto the created device
Just a nice to have when creating the device.
Useful for when running the e2es on a branch (of the upstream repo),
otherwise it will just be main cloned down and tested.
For more flexibility I am going to add a further option which will scp a
built binary (or a full tar of the local repo, can't decide yet) to make local
dev turnaround even faster.
Part of https://github.com/weaveworks/flintlock/issues/146
**Checklist**:

feat(test): Add opts to configure repo and branch

---

core/application/commands.go
hack/scripts/payload/CreateMicroVM.json

* Set `Retry` on calling Create or Delete endpoints.
* Fix CreateMicroVM payload under `hack/scripts/payload/`, it was not updated in #271 
Fixes #276
**Checklist**:

fix: MicroVM can't be deleted if it failed to create too many times

---

infrastructure/firecracker/config.go

Fix this error:
```
ERRO[0005] failed to reconcile vmid ns1/mvm1: executing plan: executing plan steps: executing steps: executing step microvm_create: creating microvm: applying firecracker configuration: putting drive configuration: [PUT /drives/{drive_id}][400] putGuestDriveByIdBadRequest  &{FaultMessage:Unable to seek the block device backing file due to invalid permissions or the file was corrupted. Error number: Is a directory (os error 21)}  controller=microvm
```
<s> I know it has zero check if RootVolume is there or not, but
1. We have validation it …

fix: root volume mount host path

---

hack/scripts/bootstrap.sh

Bootstrap Equinix machines with our new firecracker fork

feat: Bootstrap Equinix machines with our new firecracker fork

---

test/e2e/e2e_test.go

In #288 we removed the socket API listening completely.
https://pipelines.actions.githubusercontent.com/RkoJIwCv3SRvW0kQqNZsTjV9Lz9BzqDQgnc5BmuU3NzLtEIoEZ/_apis/pipelines/1/runs/3860/signedlogcontent/2?urlExpires=2021-11-30T08%3A25%3A38.8921725Z&urlSigningMethod=HMACV1&urlSignature=LOPkEpHzE%2FjHpz8wYheBl4O%2FsB5XKeE%2FhsPIS7IgdzY%3D
```
time="2021-11-30T00:13:59.703190272Z" level=debug msg="(*service).Write started" ref=works.weave.flintlockd/microvm/ns0/mvm0
e2e_test.go:65: 
Timed out after 120.000s.
Error: Assertion in callback at /root/work/flintlock/test/e2e/e2e_test.go:53 failed:
Expected
<string>: /var/lib/flintlock/vm/ns0/mvm0/firecracker.sock
to exist
```
**Checklist**:

fix: remove socket check from e2e

---

test/e2e/e2e_test.go

fix: wait for pidfile

---

infrastructure/firecracker/provider.go
internal/command/run/run.go
internal/config/config.go
pkg/defaults/defaults.go
pkg/process/process.go
pkg/process/process_test.go

Signed-off-by: Soule BA <soule@weave.works>
kind/bug
If implemented this will add a wait command to make sure a mvm is
stopped before resuming the deletion plan.
Fixes #225
**Checklist**:

Make sure a mvm is properly stopped

---

client/cloudinit/doc.go
client/cloudinit/metadata.go
client/cloudinit/network.go
client/cloudinit/userdata.go
infrastructure/firecracker/config.go

A small refactor to the **cloudinit** package to remove pointers where
possible so that its more user friendly to consume.
In the struct definitions we have tried to remove usage of pointers and instead rely on the behavior of json
marshalling and `omitempty`. Its slightly tricky with boolean values so for these we use *bool vs bool. The
reason is that the default value for some cloudinit values is true which isn't the same as the default for bool.
Fixes #
**Checklist**:

refactor: cloudinit pointer removal

---

core/application/reconcile.go
core/models/microvm.go
core/plans/microvm_create_update.go
core/plans/microvm_create_update_test.go
core/plans/microvm_delete.go
core/ports/services.go
infrastructure/grpc/convert.go
pkg/planner/actuator_test.go
pkg/planner/planner.go

4 small related pieces:
Set state to CREATED only on success
Previously we would set 'created' before any of the create steps were
even executed. Here we instead set the state to 'pending' before the
plan is compiled, and graduate to 'created' only when all steps are
complete and successful.
--
Save failed state when all create attempts fail
--
Add some more descriptive comments
To help clarify the different levels of state we have:
- The Firecracker state
- The overall (and much less verbose) Flintlock status
-- 
Reorganise grpc state conversion
It's just tidier to go in numerical order
Fixes …

Set MVM state to 'created' only on plan success

---

Makefile
core/ports/services.go
core/steps/microvm/create_test.go
core/steps/microvm/delete_test.go
core/steps/microvm/start_test.go
go.mod
go.sum
infrastructure/firecracker/provider.go
infrastructure/mock/ports.go

As we are not supporting pausing / resuming microvms at this stage these
functions have been removed from the microvm provider interface. The
firecracker implementation has these removed as well and any tests have
been updated.
Fixes #
**Checklist**:

refector: remove pause/result from provider interface

---

flintlockd.service

As part of my docs writing I realised that having an option to manage flintlockd with systemd looks a bit more pro than "start the server with an `&`".
The `--parent-iface` flag is of course required and means some sort of user input. I did consider an EnvironmentFile, but it's a bit "eh" and the systemd creators deeply regret its inclusion.
I am documenting that users need to do something here.

Add service file for systemd

---

docs/quick-start.md
hack/scripts/README.md
hack/scripts/provision.sh

provision.sh tool
Drawn a lot from firecracker's one of these, but not as much as i expected as their bits made my shellcheck yell at me a lot
There are docs included in this PR, but here is the help:
```
root@callisto:~# ./provision.sh -h
usage: ./provision.sh <COMMAND> <OPTIONS>
Script to provision hosts for running flintlock microvms
COMMANDS:
all                    Complete setup for production ready host. Component versions
can be configured by setting the FLINTLOCK, CONTAINERD and FIRECRACKER
environment variables.
OPTIONS:
-y                 Autoapprove all prompts (danger)
--skip-apt, -s     Skip installation of apt packages
--thinpool, -t     Name of thinpool to create (default: flintlock or flintlock-dev)
--disk, -d         Name blank unpartioned disk to use for direct lvm …
```

feat: provisioning script

---

flintlockd.service
hack/scripts/README.md
hack/scripts/provision.sh

This is for the provisioning script. There will be docs added.
There is an option to not do this, but by default the provision script
will assume you want a VLAN type setup.
There is a hideous little func which is sedding the flintlock service
file, and the service file itself does not look to pretty, but these are
temporary measures just for now.
Closes https://github.com/weaveworks/flintlock/issues/343
There is also a small change which will parse the lvm disk and grab the name, just in case people don't read the docs.

feat: bind flintlock server to internal ip

---

client/cloudinit/userdata.go

Adding `bootcmd` to the cloud-init user-data so that it can be used by
capmvm to temporaruily fix an issue with dns resolution in our base
images.
Fixes #
**Checklist**:

feat: exposing bootcmd cloud-init option

---

config.yaml.example
flintlockd.service
hack/scripts/README.md
hack/scripts/provision.sh

A small change to tidy up both the flintlockd.service and the
provision.sh.
Now we write a configfile for flintlockd rather than sedding flag values
into the service file.
I have also added an example config file in the repo for good measure

Update the service file to use config.yaml

---

core/application/app_test.go
core/application/commands.go
infrastructure/containerd/repo.go
test/e2e/e2e_test.go

* e2e path was not updated.
* Get tried to use empty name and namespace as a filter, not it does not
use those values if they are empty.
* UpdateMicroVM required all fields.
Related to #291 (issue)
Related to #327 (pr)
**Checklist**:

fix: uid related issues

---

.github/workflows/release.yml
.golangci.yml
Makefile
cmd/flintlock-metrics/main.go
core/ports/services.go
docs/quick-start.md
go.mod
go.sum
hack/scripts/monitoring/metrics/docker-compose.yaml
hack/scripts/monitoring/metrics/prometheus.yml
hack/scripts/payload/CreateMicroVM.json
infrastructure/firecracker/metrics.go
infrastructure/firecracker/provider.go
infrastructure/mock/ports.go
internal/command/flags/urfave.go
internal/command/metrics/main.go
internal/command/metrics/serve.go
internal/config/config.go
userdocs/docs/getting-started/extras/metrics.md

* Basic logic for the metrics exporter.
* Basic docker compose file to start a prometheus and grafana instance
for testing.
* Metrics collection under provider.
* Documentation
Fixes #210 
**Checklist**:

feat: Expose firecracker metrics

---

client/cloudinit/cloudinit.go
client/cloudinit/instance/const.go
client/cloudinit/instance/metadata.go
client/cloudinit/instance/metadata_test.go
client/cloudinit/metadata.go
client/cloudinit/network/network.go
client/cloudinit/userdata/userdata.go
client/go.mod
core/application/app_test.go
core/application/commands.go
go.mod
go.sum
infrastructure/firecracker/config.go
infrastructure/grpc/convert.go

This change will set the `instance_id` in the metadata if its not set to the UID for the microvm
Fixes #
**Checklist**:

Set instance_id in flintlock

---

test/e2e/utils/runner.go
test/tools/config/userdata.sh

Pin firecracker to v0.25.2-macvtap for e2e tests.
Can be undone after #390 
----------------------
Previously we were writing `"discard_blocks":  "true"` with `true` as a
string in the containerd config generated for the tests.
In recent containerds they are being more strict on type, so
now we set it as a bool.
Also I accidentally messed up the path, and did some weird things with other
vars. Now the containerd config file is written to
`/etc/containerd/config-e2e.toml`
not `/etc/containerd/config-e2e.toml/config-e2e.toml`.
Closes #400

Pin firecracker to `v0.25.2-macvtap` for nightly e2es

---

infrastructure/firecracker/create.go

This changes the firecracker provider to use the unique id on the VMID
for the id of the firecracker instance instead of using the
namespace/name combination. The `--id` that you supply to a firecracker
instance can only be a maximum of 64 characters. This is easily exceeded
witgh the namespace and machine name combination. We use a ULID for the
machine unique identifer internally and this is 26 characters long.
Fixes #405 
**Checklist**:

fix: failed to create microvm if machine id is too long

---

go.mod
go.sum
internal/command/flags/flags.go
internal/command/run/run.go
internal/config/config.go
pkg/auth/basic.go
pkg/auth/basic_test.go
pkg/auth/errors.go

This commit adds some very basic token-based auth to the flintlock
server.
```
flintlockd run --basic-auth-token foo
```
Note that this is not a bearer token, or a username+password combo. It
is simply a token which will be compared against an **encoded** token on
all server calls.
Clients are responsible for adding an `authorization: basic <encoded
token>` header to all calls.
Tested manually by fiddling with `hammertime`, looking to add some e2e
if possible.
TLS is next on the list.
Based upon #461 
Closes #356

feat: Add (very) basic auth

---

hack/scripts/gen_local_certs.sh

I have no idea how that got in there.

fix: Remove rogue variable

---

hack/scripts/provision.sh

This will give the option to start flintlock without basic auth or
certs.
I am adding the options for those next, just needed `--insecure` first.

feat: Add "insecure" opt to provisioner

---

README.md
hack/scripts/provision.sh

Previously flintlock only had pre-releases, which meant a different
install method in `provision.sh`. Now it can use the standard func.
Also update the compatibility table and add a note about supported
Firecracker versions.

patch: Provision flintlock from latest release

---

infrastructure/containerd/repo_test.go
infrastructure/grpc/server.go
infrastructure/grpc/server_test.go

This removes the requirement that a call to GetAllMicroVM must have a
namespace argument in the request. We do filtering on the Repo, so it is
not harmful to have all params be optional.
If a call to GetAllMicroVM is made without namespace or name, then all
mvms on the host will be returned.
If a call to GetAllMicroVM is made with just name, then all mvms
matching that name in any namespace will be returned.
If a call to to GetAllMicroVM is made with just namespace, then all mvms
under that namespace will be returned.
We can consider RBAC implications when we get to that.
**Checklist**:

feat: Add list all functionality

---

docs/quick-start.md

We have a released binary now so we don't need to tell people to build it.

Update quickstart firecracker notes

---

test/tools/config/userdata.sh

Just temporarily. The 1.6.7 release requires a newer gcc version which
means we would have to bump our ubuntu version (to get the newer gcc
easily) which comes with a few challenges. It may not be much of a big
deal at flintlock's level, but I wanted to get the nightlies working
while I figure it out.
See https://github.com/weaveworks-liquidmetal/liquid-metal-acceptance-tests/pull/11

fix: Pin containerd to 1.6.6

---

internal/command/flags/flags.go
internal/command/run/run.go
internal/config/config.go

This change adds the ability to make pprof available via http. By
default it won't be available. If you specify a debug endpoint via
`--debug-endpoint` then it will start a webserver listening at that
endpoint and pprof is available from there.
We decided to use an endpoint as that will allow users to only expose
the debug endpoint locally or via the network.
Relates #503 
**Checklist**:

feat: add pprof to flintlock

---

README.md
infrastructure/firecracker/config.go
infrastructure/firecracker/types.go

A few changes to support Firecracker v1+. We are sticking
with the v1 MMDS initially and will look to upgrade to the v2 MMDS in
the future.
To use this version with macvtap we will need to use our fork with the
1.1 changes.
NOTE: incorrect serialization caused the issues with MMDS not working.
Strangely Firecracker didn't complain about the invalid json config.
Time and stress wasted on what was essentially a typo. ffs.
Fixes #390 
**Checklist**:

feat: add support for Firecracker v1+

---

test/tools/config/userdata.sh

With adding support for Firecracker v1.0+ we need remove pinning to the
old version of our fork.
Fixes #
**Checklist**:

chore: remove pinning of the firecracker version

---

core/application/reconcile.go
core/ports/usecases.go
infrastructure/controllers/microvm_controller.go
infrastructure/controllers/microvm_controller_test.go
internal/inject/wire.go
internal/inject/wire_gen.go

The resynce functionality has been moved to the controller. This means
the core application know how to do CRUD on the vmspecs and how to
reconcile a single vm spec.
Functionality such as resynce can be orchestrated via calls to the core
app.
Signed-off-by: Richard Case <richard.case@outlook.com>
Fixes #520 
**Checklist**:

refactor: moved resync to controller

---

client/cloudinit/network/network.go
infrastructure/firecracker/config.go

This change will force DHCP to use the mac address as the client
identifier when requesting a mac address. Without this (depending on
your distro) it may not use a mac address and the mv may not get a ip
address assigned to it.
Signed-off-by: Richard Case <richard.case@outlook.com>
Fixes #518 
**Checklist**:

feat: force dhcp to use mac as client identifier

---

Vagrantfile

Previously, using the Vagrantfile required cloning the Flintlock repo because it was reading `scripts/devpool.sh` and `scripts/example-config.toml` from a local path. Now, it curls these scripts so that the Vagrantfile can be used independently from the repo. :)
**Checklist**:

Curl scripts to make Vagrantfile self-contained

---

go.mod
go.sum
pkg/cloudhypervisor/client.go
pkg/cloudhypervisor/handlers.go
pkg/cloudhypervisor/types.go

This change adds a Cloud Hypervisor API client. This will be used in a
later implementation to enable Flintlock to talk to running instances of
Cloud Hypervisor.
Relates #417 
This functionality will not be used initially.
**Checklist**:

feat: cloudhypervisor api client

---

Vagrantfile

kind/bug
Remove the setting up in the vagrant file, as some of it got outdated. Also, the provision script and the setup guide involve running commands in a specific way. And thus, doing it in the Vagrant file only messes with this process rather than aid it.
It also adds public networking so calls to downloads and such still work.
Fixes https://github.com/weaveworks-liquidmetal/site/issues/11
**Checklist**:

Remove duplicated vagrantfile scripting

---

hack/scripts/provision.sh

edit: Actually realised I don't like the flags and that the idea in #549 is correct: we should detect.
Also take care of any backwards compatibility for those downloading earlier firecracker versions which were named differently.
Closes #376 
Closes #548

feat: Update provision.sh to detect arch

---

hack/scripts/provision.sh

This is a small fix to change the name of the containerd systemd service to `containerd-dev.service` when deployed with `--dev`. Previously systemctl commands in the script were issued to the `containerd.service`.
Fixes #548 
**Checklist**:

fix: issue systemctl commands to the correct containerd service

---

hack/scripts/provision.sh

Flintlock depends on containerd so it should wait for it to become available and stop when the containerd service stops.
In a dev environment, the containerd service may be running under another name, so flintlock should watch the correct one.

fix: Edit service file to wait on containerd

---

test/e2e/utils/utils.go

we kept hitting docker rate limits with richard's old images

test: use our ghcr images in e2es

---

.github/workflows/deploy-docs.yaml

I don't know why github didn't want to see the old one, even when I
replaced it.
Now with the same key under a new name it is fine so.... yeh.

Rename docs deploy key

---

CONTRIBUTING.md
README.md
docs/image-creation.md
docs/quick-start.md
flintlockd.service
userdocs/docusaurus.config.js

The old domain is broken for a time

fix: Publish docs under github.io domain

---

.github/workflows/release.yml

The e2es have been off for a while since I lost auth powers to create new projects in Equinix. Since then something weird has happened and the tests fail strangely for different reasons.
I have performed all the test steps manually several times (all they do is simple CRUD operations on flintlock) and the code seems fine. I have also used this version of flintlock to create a few capmvm clusters. So I am confident that the problem is with the tests and not the code.
I am disabling the test step of the release process so that I can release flintlock and capmvm (thus close off a large image-builder epic) before I circle back to figure out what is going on with these tests.

Temporarily disable pre-release tests

---

.github/workflows/dependabot_bundler.yml
CONTRIBUTING.md

The bundler PRs are getting out of control. Let's try and rein them in.
This will also add the correct label so the label checker doesn't croak.
kind/feature
Fixes #
**Checklist**:

chore(deps): add dependabot bundler

---

CONTRIBUTING.md

chore(ref): add examples for dependabot bundler

---

.github/workflows/dependabot_bundler.yml

kind/feature
The dependabot bundler was missing a `go mod tidy` after performing `go get` which could end up leaving the mod files dirty.
Fixes #
**Checklist**:

chore(deps): this release adds go mod tidy after the updates

---

hack/scripts/provision.sh
infrastructure/containerd/image_service.go
infrastructure/microvm/firecracker/create.go

kind/bug
Modify provision.sh to accept a custom GRPC port using -p or --grpc-port. Currently we hardcode 9090 and provide no way to override it.
Fix a couple of return statements using the wrong error
Fixes #568 
**Checklist**:

modify provision.sh to accept grpc port

---

.github/workflows/fork.yaml
.github/workflows/nightly_e2e.yml

The mentioned channel was archived.
[Potentially in the future](https://github.com/weaveworks-liquidmetal/flintlock/issues/730) we can redirect it to the the [community channel](https://weave-community.slack.com/archives/C02KARWGR7S), but that would require changes to the secret and it's easier to just change to that channel for now.

move notification to #liquid-metal-dev from #team-quick-silver

---

infrastructure/grpc/convert.go

Added missing provider to convert method
Fixes #
**Checklist**:

adding provider to convert
